@node overview
@chapter Overview

@code{vise} is a virtual machine specialized for generating output for clients that have strict output size constaints.

Specifically, the original target enviromnent was USSD menu navigation and session handling.

@section Features

@section Contents

@subsection Virtual machine

This component processes menu navigation from client input, and executes 

@itemize
@item Virtual machine to handle menu navigation.
@item Assembly mini-language to script for the virtual machine.
@item Code interface for external calls.
@end itemize
